### ISSUE TITLE
Not creating new folders in media for existing media libraries moved to S3...

### ISSUE THREAD

**Issue by john-mckillip** [ElijahGlover/Umbraco-S3-Provider#1]
Hi, 

So I am running into an issue. I have a website that multiple developers are working locally on and pushing changes to Github. I have an existing project, which I moved the media folder into S3. After I made the changes in FileSystemProviders.config and started uploading media, it went into my S3 bucket okay, but instead of creating a new folder under media, it puts the image in the already existing 1001 folder, which creates and issue because only one image can have that id. 

I did a test and uploaded a bunch of test images to trick it into finally getting through all the existing image folders, which it did, and then it started creating new ones. Then I pushed everything to Github, and when another developer synced and tested the media upload, it defaulted back to folder 1001. Wondering if there is a reason why it is doing this. Please let me know if any of this makes sense.
Thanks!

John

**Comment by john-mckillip** [comment]
Also, I should have noted that I am using Umbraco v.7.2.2. Not sure if that makes a difference or not,

**Comment by ElijahGlover** [comment]
Due to the limitations of Umbraco's FileSystem provider it's not possible to share the same bucket/prefix with multiple developer databases. Umbraco generates the S3 storage key/path using the associated primary key on the cmsPropertyData table.

Elijah

**Comment by john-mckillip** [comment]
Sorry, I should have been more clear. There are multiple developers, one database. For some reason, if I make a change to ClientDependency.config or someone clones my repository and builds, it defaults the media folder back to 1001 on the S3 side.

John

**Comment by ElijahGlover** [comment]
I've had a play with multiple umbraco 7.2.2 application pools and are able to see what your talking about. It looks to me like the implementation was recently changed in v7 [d73dd47](https://github.com/umbraco/Umbraco-CMS/blob/ded1def8e2e7ea1a4fd0f849cc7a3f1f97cd8242/src/Umbraco.Core/Media/MediaSubfolderCounter.cs) relying on MediaSubfolderCounter to hold a counter.

I've updated the S3 file system provider to query and return the correct last used id. The bad news is Umbraco holds reference and increments it per environment making it almost impossible to have multiple backoffices/developers uploading media without overlapping media paths.

You might be able to work some reflection magic and keep calling the constructor in a timer to continually to keep the counter up to date. For large media libraries this would be problematic as you would be making a substantial amount of requests due to continuation requests.

**Comment by john-mckillip** [comment]
Hi Elijah,
Thanks for your time on this. 
Cheers!
