### ISSUE TITLE
Media library ImageCropper not showing preview image

### ISSUE THREAD

**Issue by SENSiXWebDev** [ElijahGlover/Umbraco-S3-Provider#10]
Firstly, great work on this! Question: I followed all setup instructions and its working fine and is uploading to S3 as expected. In the media folder on the media item (ImageCropper) once uploaded, if you click out and back in again no previews show on main image or any of the crops and no crops are created on S3. Is there a way to configure this for a seamless backend experience? How can I configure Umbraco to still be able use the backoffice media section to manage the uploads, crops and previews whilst the images and crops are stored in S3? Any ideas on this?

Interestingly you do get a preview if you click on the containing folder of the media item but not if you click into the item itself. My client needs to be able to upload and edit crops as before but it stores everything in S3 instead of in the local file system.

**Comment by cheeseytoastie** [comment]
I think you may have had the same issue I just did. 

I found a note on the Azure setup here https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure#combining-with-imageprocessor

That worked for me on S3. Basically you need to set the VPP in the Media directory itself (apparently in Umbraco v7.5+).

Hope this helps someone else with this issue. If it's correct perhaps it needs to go in the Readme.Md? 

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<system.webServer>
		<handlers>
			<clear />
			<add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler" />
			<add name="StaticFile" path="*" verb="*" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" resourceType="Either" requireAccess="Read" />
		</handlers>
	</system.webServer>
</configuration>`

**Comment by fe-vko** [comment]
@cheeseytoastie I have a similar issue and what you posted didn't solve it for me, but made it worse. Maybe somewhere in the other configs I got something wrong.

When I added the second line (<add name="StaticFile".....) the server wasn't able to read any of the images.

Can you show me all your configs to compare (obv remove your bucket names and keys etc...).

I made a topic in umbraco and also in Stackoverflow for a more detailed explanation: https://our.umbraco.org/forum/using-umbraco-and-getting-started//85137-aws-s3-cloudfront-s3-plugin-and-imageprocessor-super-slow-image-loading
http://stackoverflow.com/questions/43468923/super-slow-performance-between-umbraco-and-aws-s3-bucket-for-images-and-cached-i

For me the problem is, it is super slow. They load up eventually, but takes a while especially when you open up a folder with images (either in the backoffice or a gallery on the front end).
